source :rubygems

gem 'rails', '~>3.0.10'

gem 'activeadmin'
gem 'cancan'
gem 'capistrano'
gem 'carrierwave'
gem 'delayed_job'
gem 'formtastic'
gem 'devise'
gem 'fog'
gem 'foreman'
gem 'heroku'
gem 'inherited_resources'
gem 'jquery-rails'
gem 'kaminari'
gem 'newrelic_rpm'
gem 'omniauth', '~>0.3.2'
gem 'pg'
gem 'rmagick'
gem 'sass'
gem 'unicorn'

group :test, :development do
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'guard'
  gem 'cucumber'
  gem 'capybara'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'ruby-debug19'
  gem 'rb-fsevent'
  gem 'growl'
end
